### ISSUE TITLE
Do you use overflow-wrap when the text is line breakable

### ISSUE THREAD

**Issue by xianshenglu** [xianshenglu/blog#139]
Let's assume that you need to display a paragraph in multiple lines. How would you do that?

For example,

```html
<div class="wrapper">
  <p class="text">
    a long long long long long long long long long long paragraph
  </p>
</div>
```

```css
.wrapper {
  width: 200px;
  background-color: pink;
}
```

![image](https://github.com/xianshenglu/blog/assets/23273077/e403092e-da7d-4fc7-b0e0-578b276d3f8d)

Normally, it's enough.

However, **if the text can be controlled by other sources, for example, user input. Then it'll not be ok.**

For example,

```html
<div class="wrapper">
  <p class="text">
    a long_long_long_long_long_long_long_long_long_long_ paragraph
  </p>
</div>
```

```css
.wrapper {
  width: 200px;
  background-color: pink;
}
```

![image](https://github.com/xianshenglu/blog/assets/23273077/2ea6cc00-7ef8-4b9e-8270-0321cab9315d)

The solution I found is

```css
.wrapper {
  width: 200px;
  background-color: pink;
  overflow-wrap:break-word;
}
```

![image](https://github.com/xianshenglu/blog/assets/23273077/03e0bdb8-8f59-48c5-97a8-02c96179ab02)

## Other possible solutions

- Actually, you can also use `word-break: break-word;`. However, it's `depreciated`.

[Article Source](https://github.com/xianshenglu/blog/issues/139)
