### ISSUE TITLE
img without src would have 1px white border on mobile on chrome.

### ISSUE THREAD

**Issue by xianshenglu** [xianshenglu/blog#37]
set default src to avoid this, also onerror is needed.

**Comment by xianshenglu** [comment]
or 

```css
img[src=''],
img:not([src]) {
  opacity: 0;
}
```
